# Generated by Django 5.2.10 on 2026-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGOActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('max_employees', models.IntegerField()),
                ('current_slots_taken', models.IntegerField(default=0)),
                ('cut_off_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
